name: Build and Deploy to Docker hub

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. JDK 설치
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Gradle Wrapper 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 4. 프로젝트 빌드
      - name: Build project
        run: ./gradlew clean build

      # 5. Docker 이미지 업로드
      - name: Build Docker image
        run: sudo docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-module-test:latest .

      # 6. 도커 허브 로그인
      - name: Login to Docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 7. 도커 허브 푸시
      - name: Push Docker image
        run: sudo docker push ${{ secrets.DOCKER_USERNAME }}/multi-module-test:latest

      # 8. 컨테이너 실행
      - name: Deploy Docker container
        run: |
          docker stop spring-app || true
          docker rm spring-app || true
          docker run -d -p 8080:8080 --name spring-app ${{ secrets.DOCKER_USERNAME }}/multi-module-test:latest
